app:
  host: 127.0.0.1
  port: 5000

database: mongodb+srv://xuannam:xuannamt81@web.qpw3q.mongodb.net/thesis-question

intent_slot_service:
  url: localhost:5002

action_decider_service:
  url: localhost:5003

post_slot_service:
  url: localhost:5002

redis:
  host: 127.0.0.1
  port: 6379
  password:

clickhouse:
  host: xe9pfzmzgi.eu-west-1.aws.clickhouse.cloud
  port: 8443
  username: default
  password: JZDfmD8IAwxJ~

elasticsearch: 
  url: http://localhost:9200
  cloud_id:
  user:
  password:

crawler:
  fanpage_links: groups/cse.ctxh,BKCSE.Multimedia
  cookie_path: data/facebook.com_cookies.txt
  page_number: 100
